//! Typed response structs for Technitium API responses.
//!
//! `RecordData` in types.rs covers records you can *add or delete*.
//! `ReadOnlyRecordData` here covers records that are server-managed and
//! only ever appear in list_records responses — never in add/delete calls.

use schemars::JsonSchema;
use serde::{Deserialize, Serialize};

use crate::core::dns::records::{DsAlgorithm, RecordData};
use crate::core::error::{Error, Result};

// ─── Read-only DNSSEC record data ─────────────────────────────────────────────

/// DNSKEY — public key record, managed by Technitium's DNSSEC key lifecycle.
/// Created when you publish a private key; retired via the DNSSEC key API.
#[derive(Debug, Clone, Serialize, Deserialize, JsonSchema)]
#[serde(rename_all = "camelCase")]
pub struct DnskeyData {
    pub flags: u16,
    /// Always 3 per RFC 4034
    pub protocol: u8,
    pub algorithm: DsAlgorithm,
    /// Base64-encoded public key
    pub public_key: String,
    pub computed_key_tag: u16,
    /// Active | Ready | Generated | Retired
    pub dns_key_state: Option<String>,
    pub is_ksk: Option<bool>,
}

/// RRSIG — signature over a record set, generated automatically on every write.
/// Technitium refreshes these before expiry; you cannot add or remove them directly.
#[derive(Debug, Clone, Serialize, Deserialize, JsonSchema)]
#[serde(rename_all = "camelCase")]
pub struct RrsigData {
    pub type_covered: String,
    pub algorithm: DsAlgorithm,
    pub labels: u8,
    pub original_ttl: u32,
    /// ISO 8601 datetime
    pub signature_expiration: String,
    /// ISO 8601 datetime
    pub signature_inception: String,
    pub key_tag: u16,
    pub signer_name: String,
    /// Base64-encoded signature
    pub signature: String,
}

/// NSEC — proof of non-existence (ordered linked list of zone names).
/// Generated by the signing engine; not manually manageable.
#[derive(Debug, Clone, Serialize, Deserialize, JsonSchema)]
#[serde(rename_all = "camelCase")]
pub struct NsecData {
    pub next_domain_name: String,
    /// Record types present at this name, e.g. ["A", "RRSIG", "NSEC"]
    pub types: Vec<String>,
}

/// NSEC3 — hashed proof of non-existence.
/// Generated by the signing engine; not manually manageable.
#[derive(Debug, Clone, Serialize, Deserialize, JsonSchema)]
#[serde(rename_all = "camelCase")]
pub struct Nsec3Data {
    pub hash_algorithm: String,
    pub flags: u8,
    pub iterations: u16,
    /// Hex-encoded salt
    pub salt: String,
    pub next_hashed_owner_name: String,
    pub types: Vec<String>,
}

/// Record types that appear in list_records responses but cannot be
/// added or deleted via the record API.
#[derive(Debug, Clone, Serialize, Deserialize, JsonSchema)]
#[serde(tag = "type", rename_all = "UPPERCASE")]
pub enum ReadOnlyRecordData {
    Dnskey(DnskeyData),
    Rrsig(RrsigData),
    Nsec(NsecData),
    Nsec3(Nsec3Data),
}

// ─── Unified record data ──────────────────────────────────────────────────────

/// Any record that can appear in a list_records response — either a writable
/// record (add/delete supported) or a read-only server-managed DNSSEC record.
#[derive(Debug, Clone, Serialize, Deserialize, JsonSchema)]
#[serde(untagged)]
pub enum AnyRecordData {
    Writable(RecordData),
    ReadOnly(ReadOnlyRecordData),
}

// ─── Zone record entry ────────────────────────────────────────────────────────

/// A single DNS record as returned by the list_records API.
#[derive(Debug, Clone, Serialize, Deserialize, JsonSchema)]
#[serde(rename_all = "camelCase")]
pub struct ZoneRecord {
    pub name: String,
    #[serde(rename = "type")]
    pub record_type: String,
    pub ttl: u32,
    #[serde(default)]
    pub disabled: bool,
    #[serde(default)]
    pub comments: String,
    #[serde(default)]
    pub expiry_ttl: u64,
    #[serde(rename = "rData")]
    pub data: serde_json::Value,
    /// Parsed typed form — None if the type is unrecognised
    #[serde(skip)]
    pub parsed: Option<AnyRecordData>,
}

impl ZoneRecord {
    /// Typed record data for this record. Uses the pre-parsed value when one is
    /// present, otherwise parses on demand from `record_type` + `data` — so it
    /// works regardless of which vendor produced the record.
    pub fn typed(&self) -> Option<AnyRecordData> {
        if let Some(parsed) = &self.parsed {
            return Some(parsed.clone());
        }
        parse_record_data(&self.record_type, &self.data)
    }
}

// ─── List records response ────────────────────────────────────────────────────

#[derive(Debug, Clone, Serialize, Deserialize, JsonSchema)]
#[serde(rename_all = "camelCase")]
pub struct ZoneInfo {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    pub name: String,
    #[serde(rename = "type")]
    pub zone_type: String,
    #[serde(default)]
    pub disabled: bool,
    pub dnssec_status: Option<String>,
}

/// Records for a single DNS zone.
#[derive(Debug, Clone, Serialize, Deserialize, JsonSchema)]
pub struct ZoneRecords {
    pub zone: ZoneInfo,
    pub records: Vec<ZoneRecord>,
}

/// Response from list_records — may contain one zone or many (e.g. Pangolin "list all").
///
/// **Serialization shape:**
/// - Single zone → `{"zone": {...}, "records": [...]}` (flat, matches the historical shape)
/// - Multiple zones → `{"zones": [{"zone": {...}, "records": [...]}, ...]}`
#[derive(Debug, Clone)]
pub struct ListRecordsResponse {
    pub zones: Vec<ZoneRecords>,
}

impl serde::Serialize for ListRecordsResponse {
    fn serialize<S: serde::Serializer>(&self, s: S) -> std::result::Result<S::Ok, S::Error> {
        use serde::ser::SerializeMap;
        match self.zones.as_slice() {
            [single] => {
                let mut map = s.serialize_map(Some(2))?;
                map.serialize_entry("zone", &single.zone)?;
                map.serialize_entry("records", &single.records)?;
                map.end()
            }
            _ => {
                let mut map = s.serialize_map(Some(1))?;
                map.serialize_entry("zones", &self.zones)?;
                map.end()
            }
        }
    }
}

impl<'de> serde::Deserialize<'de> for ListRecordsResponse {
    fn deserialize<D: serde::Deserializer<'de>>(d: D) -> std::result::Result<Self, D::Error> {
        #[derive(Deserialize)]
        #[serde(untagged)]
        enum Repr {
            Multi {
                zones: Vec<ZoneRecords>,
            },
            Single {
                zone: ZoneInfo,
                records: Vec<ZoneRecord>,
            },
        }
        match Repr::deserialize(d)? {
            Repr::Multi { zones } => Ok(Self { zones }),
            Repr::Single { zone, records } => Ok(Self::single(zone, records)),
        }
    }
}

impl ListRecordsResponse {
    /// Convenience constructor for the common single-zone case.
    pub fn single(zone: ZoneInfo, records: Vec<ZoneRecord>) -> Self {
        Self {
            zones: vec![ZoneRecords { zone, records }],
        }
    }

    /// Parse the raw Technitium API JSON into a typed response, populating
    /// `parsed` on each record where the type is recognised.
    pub fn from_value(value: &serde_json::Value) -> Result<Self> {
        let response = value
            .get("response")
            .ok_or_else(|| Error::parse("list_records response missing 'response' key"))?;

        let mut zone: ZoneInfo = serde_json::from_value(
            response
                .get("zone")
                .ok_or_else(|| Error::parse("list_records response missing 'response.zone'"))?
                .clone(),
        )
        .map_err(|e| Error::parse(format!("could not deserialize zone info: {e}")))?;
        if zone.id.is_none() {
            zone.id = Some(zone.name.clone());
        }

        let raw_records = response
            .get("records")
            .and_then(|r| r.as_array())
            .ok_or_else(|| {
                Error::parse("list_records response missing 'response.records' array")
            })?;

        let records = raw_records
            .iter()
            .filter_map(|r| {
                let mut record: ZoneRecord = serde_json::from_value(r.clone()).ok()?;
                record.parsed = parse_record_data(&record.record_type, &record.data);
                Some(record)
            })
            .collect();

        Ok(Self::single(zone, records))
    }
}

fn parse_record_data(record_type: &str, rdata: &serde_json::Value) -> Option<AnyRecordData> {
    // Reconstruct the tagged value that serde expects for RecordData / ReadOnlyRecordData
    let mut tagged = rdata.clone();
    if let Some(obj) = tagged.as_object_mut() {
        obj.insert(
            "type".into(),
            serde_json::Value::String(record_type.to_uppercase()),
        );
    }

    // Try writable first, then read-only
    if let Ok(w) = serde_json::from_value::<RecordData>(tagged.clone()) {
        return Some(AnyRecordData::Writable(w));
    }
    if let Ok(ro) = serde_json::from_value::<ReadOnlyRecordData>(tagged) {
        return Some(AnyRecordData::ReadOnly(ro));
    }
    None
}

// ─── Tests ────────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests;
